-- SOSTITUITO: non eseguire più questo script.
-- Le policy e i trigger aggiornati sono in supabase/migrations/20260916090200_privacy_statistiche.sql.
-- Rieseguire la versione precedente annullerebbe le correzioni di sicurezza.
